export interface InstitutionStudent {
  regNumber: string;
  fullName: string;
  faculty: string;
  department: string;
  admissionYear: number;
  expectedGraduationYear: number;
  gender: string;
  phoneNumber: string;
  email: string;
  dateOfBirth: string; // YYYY-MM-DD
  stateOfOrigin: string;
  address: string;
  nextOfKin: string;
  nextOfKinGSM: string;
  nextOfKinAddress: string;
}

export const mockInstitutionDB: InstitutionStudent[] = [
  {
    "regNumber": "U23CS2066",
    "fullName": "Zayyan Abdullahi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2066@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2065",
    "fullName": "Umar Sumaiya Njobdi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2065@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2064",
    "fullName": "ABDULLAHI MUBARAK YUSUF",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2064@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2063",
    "fullName": "Zainab Hussain",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2063@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2060",
    "fullName": "Okeke Francis",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2060@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2057",
    "fullName": "Idris abdullahi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2057@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2056",
    "fullName": "Saeed Bashir",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2056@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2055",
    "fullName": "Muhammad Nasiru",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2055@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2052",
    "fullName": "Idriss Oussama Ahmat",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2052@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2051",
    "fullName": "Musa Ahmad Kalamullah",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2051@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2050",
    "fullName": "HABIBA ASHAFA",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2050@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2049",
    "fullName": "Abdulrahman Aminu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2049@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23cs2048",
    "fullName": "Sabo fahad",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2048@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2047",
    "fullName": "Salisu Saidu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2047@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2045",
    "fullName": "Usamah Sumayya Imam",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2045@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2044",
    "fullName": "Safiyya Muhammad Nasir",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2044@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2043",
    "fullName": "Mubarak Muhammad",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2043@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2042",
    "fullName": "Abdullahi Hafsat",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2042@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2041",
    "fullName": "Rilwan Abdullahi Muhammad",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2041@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2040",
    "fullName": "Zainab Ismail Ibrahim",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2040@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2039",
    "fullName": "Amina Yusuf",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2039@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2038",
    "fullName": "Ibrahim Fatima Shehu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2038@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2037",
    "fullName": "USAMA IBRAHIM",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2037@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2036",
    "fullName": "Kamaludeen lawal idris",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2036@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2035",
    "fullName": "UMAR FARUK ISHAQ",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2035@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2034",
    "fullName": "Ibrahim Bashir Ishaq",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2034@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1069",
    "fullName": "Aliyu Ibrahim",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1069@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2032",
    "fullName": "Abdulmalik Halimatu sadiya",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2032@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2031",
    "fullName": "Safiya hamza",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2031@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2030",
    "fullName": "Habib Khadija Abdulkadir",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2030@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2029",
    "fullName": "Suleiman Ibrahim Tanko",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2029@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2027",
    "fullName": "Hussain Faruk Shazhin",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2027@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2026",
    "fullName": "ABDULLAHI, Bashir Muhammed",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2026@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2025",
    "fullName": "ABDURRAZAK HASSAN ADAMU",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2025@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2024",
    "fullName": "Yusuf Ahmad Zakari",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2024@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2023",
    "fullName": "Usman Dedah Migana",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2023@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2022",
    "fullName": "Jamila muazu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2022@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2021",
    "fullName": "Ganiyu Sefiat",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2021@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2018",
    "fullName": "Mohammed Abubakar Sadiq",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2018@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2017",
    "fullName": "Musa Hussaini Kidandan",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2017@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2016",
    "fullName": "Dahiru Kamaludeen Ibrahim",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2016@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2015",
    "fullName": "Abubakar mustapha",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2015@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2014",
    "fullName": "Bambale Habiba Nasiru",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2014@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2012",
    "fullName": "Sa'adiya Ahmad Abdullahi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2012@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2011",
    "fullName": "Abdulhamid Adamu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2011@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2010",
    "fullName": "MOHAMMED ZANNA BILKISU",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2010@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2009",
    "fullName": "Abdulwaheed Umar farouk",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2009@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2008",
    "fullName": "ABDULHAMID YAHYA JUMARE",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2008@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2007",
    "fullName": "Aisha Aminu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2007@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2006",
    "fullName": "Bashir Aminu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2006@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2005",
    "fullName": "JAMILU BALA",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2005@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2004",
    "fullName": "Munnir Sagir",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2004@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2003",
    "fullName": "Umar balarabe",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2003@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2002",
    "fullName": "Shuaibu fatima Hassan",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2002@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2001",
    "fullName": "Tauheed Iliyasu lawal",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2001@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS2094",
    "fullName": "Abdulrashid Abdullahi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs2094@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS2065",
    "fullName": "Muhammad Sani",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs2065@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS2032",
    "fullName": "Ibrahim Alhaji Muhammed",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs2032@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS2003",
    "fullName": "Abdulaziz Ahmad Abdul",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs2003@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1150",
    "fullName": "Abdullahi Isa Abdullahi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1150@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1149",
    "fullName": "Hassan Idris",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1149@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1147",
    "fullName": "Suleiman Nasir Ladan",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1147@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1146",
    "fullName": "Khalid Habib",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1146@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1145",
    "fullName": "Abdulhamid Fatima",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1145@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1144",
    "fullName": "Adedigba Jamiu Adeniyu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1144@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1143",
    "fullName": "Abubakar Abdulmalik Datti",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1143@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1142",
    "fullName": "Abdulhamid Shukrah Morenikeji",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1142@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1141",
    "fullName": "Ahmed Abdulazeez",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1141@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1140",
    "fullName": "Kough Benjamin Terungwa",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1140@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1139",
    "fullName": "IRO ABDULHAKEEM IBRAHIM",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1139@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1138",
    "fullName": "Banes Sossou Peter",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1138@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1137",
    "fullName": "SUHAIL ALIYU SAID",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1137@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1134",
    "fullName": "BALARABE BASHIR Z",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1134@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1133",
    "fullName": "Abdulaziz mujahid halliru",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1133@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1132",
    "fullName": "Muhammad Abdullahi Musa",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1132@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1130",
    "fullName": "Bright Unwana Bassey",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1130@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1129",
    "fullName": "Mustapha muhammad ohiare",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1129@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1128",
    "fullName": "Abdullawi Abdullahi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1128@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1127",
    "fullName": "Ikomkeh Hegen James",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1127@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1126",
    "fullName": "Achuja Isah Rasheedat",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1126@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1125",
    "fullName": "Lauratu Naiya Sada",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1125@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1124",
    "fullName": "Jibrin Adamu Ahmed",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1124@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1121",
    "fullName": "Muhammad nura isah",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1121@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1120",
    "fullName": "Ibrahim Maimuna",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1120@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1119",
    "fullName": "Jesutoyin Adeshina",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1119@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1118",
    "fullName": "IWE LUCKY JOHN",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1118@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1117",
    "fullName": "Umaru sani Mohammed",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1117@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1116",
    "fullName": "Mubarak Yusuf",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1116@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1115",
    "fullName": "Abdulrahman Habeeb Adewale",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1115@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1114",
    "fullName": "Yakubu Khalid",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1114@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1113",
    "fullName": "Abdullahi Rabiu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1113@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1112",
    "fullName": "Abiina Marvellous Tolulope",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1112@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1110",
    "fullName": "Ehikoowoicho Matthew Alfred",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1110@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1108",
    "fullName": "Lukman Adamu Jibrin",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1108@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1107",
    "fullName": "Emmanuel Agiende Ushie",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1107@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1106",
    "fullName": "Abdulrahmon Abubakar",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1106@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1105",
    "fullName": "Abdullahi Abdulhamid",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1105@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1103",
    "fullName": "Shenge Mark Oryiman",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1103@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1102",
    "fullName": "Adeyemo David Adedayo",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1102@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1101",
    "fullName": "ONUORAH Clinton Nnamdi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1101@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1100",
    "fullName": "Ibrahim Tukur Nuhu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1100@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1098",
    "fullName": "SALIHU ABUBAKAR SADIQ",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1098@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1097",
    "fullName": "Fathia Adekeye",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1097@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1096",
    "fullName": "ONYUMA JOHN",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1096@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1095",
    "fullName": "Abdulmajid hamza",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1095@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1094",
    "fullName": "Jimoh Abdulrasheed Olarewaju",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1094@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1092",
    "fullName": "Abubakar Onuroyiza Sadiq",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1092@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1090",
    "fullName": "Umar Farouq Ibrahim",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1090@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1089",
    "fullName": "Badamasi Idris",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1089@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1086",
    "fullName": "Aliyu Ibrahim Abubakar",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1086@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1085",
    "fullName": "Zainab idris usman",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1085@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1083",
    "fullName": "Fatiha Abdullateef Yusuf",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1083@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1081",
    "fullName": "Isma'il Usman Suleiman",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1081@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1079",
    "fullName": "Emmanuel Iortyange",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1079@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1078",
    "fullName": "Attahiru Khalifa Atto",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1078@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1077",
    "fullName": "Joseph Friday Asuku",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1077@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1076",
    "fullName": "Irhiawo oyaighua saadiq",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1076@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1075",
    "fullName": "Zaid Husaini",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1075@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1074",
    "fullName": "Yari Desmond Bala",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1074@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1072",
    "fullName": "Muhammad Al-amin Alkali",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1072@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1071",
    "fullName": "Gyabbi Chumnom",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1071@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1070",
    "fullName": "Habib Abdulrahman",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1070@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1068",
    "fullName": "Ibrahim Aminu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1068@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1067",
    "fullName": "BILAL ALHUSSAIN",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1067@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1066",
    "fullName": "AlJannat Adeola Uthman",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1066@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1064",
    "fullName": "Khaleel Ibrahim",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1064@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1063",
    "fullName": "Hussaini sabiu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1063@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1062",
    "fullName": "Ahmad Saminu Idris",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1062@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1059",
    "fullName": "Woje Isaac Tisan",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1059@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1058",
    "fullName": "Salisu Ahmad",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1058@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1057",
    "fullName": "Adamu Muhammed Rabiu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1057@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1056",
    "fullName": "Idris Ahmad",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1056@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1055",
    "fullName": "Uwem Emmanuel Bassey",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1055@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1053",
    "fullName": "Abdulkadir Khalifa Abba",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1053@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1051",
    "fullName": "Mohammed Usman Uba",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1051@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1050",
    "fullName": "Ammar Muhammad",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1050@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1049",
    "fullName": "Idris Sheikh Ibrahim Inyas",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1049@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1048",
    "fullName": "OYEWOLE EMMANUEL OYENIYI",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1048@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1047",
    "fullName": "MUHAMMED ALIYU",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1047@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1046",
    "fullName": "Mu'azu Sulaiman Idris",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1046@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1045",
    "fullName": "Yahaya Abdulrazaq",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1045@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1043",
    "fullName": "Lois Onozasi Ahmed",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1043@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1042",
    "fullName": "Ikram Shehu gada",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1042@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1041",
    "fullName": "Safeeyah Ameerah Abubakar",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1041@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1040",
    "fullName": "Kolobe Muhammad Annur",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1040@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1039",
    "fullName": "Abdulqadir, Basheer Ibrahim",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1039@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1038",
    "fullName": "Mustapha Muhammad",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1038@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1036",
    "fullName": "Nanbol Joseph Nannim",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1036@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1035",
    "fullName": "Abdurrahman Nasir Umar",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1035@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1032",
    "fullName": "Kusheish Azi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1032@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1031",
    "fullName": "Usamah Sulaiman karwai",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1031@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1028",
    "fullName": "Praise Somtochukwu Orji",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1028@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1026",
    "fullName": "Izuchukwu Raymond Godwin",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1026@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1025",
    "fullName": "Jacob Christopher galadima",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1025@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1024",
    "fullName": "Auwal Maryam jibo",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1024@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1023",
    "fullName": "Sani, Abdurrahman Ishaq",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1023@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1022",
    "fullName": "Abdulmalik Ibrahim",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1022@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1020",
    "fullName": "Abdulquadri Sofeeyat",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1020@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1019",
    "fullName": "ALIYU ADO GARBA",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1019@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1018",
    "fullName": "Abdulrahman Abdulhakeem",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1018@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1017",
    "fullName": "Yusuf Babangida Minkail",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1017@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1016",
    "fullName": "Abdusshakur Olabisi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1016@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1015",
    "fullName": "Abdulazeez Olawale Bolakale",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1015@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1014",
    "fullName": "Mustapha Sani",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1014@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1013",
    "fullName": "Tochukwu Emmanuel Mgbe",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1013@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1010",
    "fullName": "Ibrahim Sulaiman",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1010@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1008",
    "fullName": "Mujahid Yusuf Dan-audi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1008@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1007",
    "fullName": "Mustapha Mujaheed Idris",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1007@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1006",
    "fullName": "Mubarak Abdullahi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1006@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1005",
    "fullName": "Yusuf Paul",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1005@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1003",
    "fullName": "Yusuf precious Monday",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1003@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1002",
    "fullName": "NOAH NOMSU AUDU",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1002@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U19CS1128",
    "fullName": "Faisal Lawal Ahmed",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u19cs1128@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U23CS2033",
    "fullName": "Imrana Aliyu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u23cs2033@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1054",
    "fullName": "Jumare Abdullahi",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1054@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1044",
    "fullName": "Hamza Abdulazeez Nggada",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1044@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1034",
    "fullName": "Bzigu Joseph chinda",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1034@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1021",
    "fullName": "Ibrahim Hassan",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1021@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U21CS1011",
    "fullName": "Buhari Abdurrahman Shehu",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u21cs1011@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U19CS1081",
    "fullName": "PAUL BUKAR JUNIOR",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u19cs1081@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  },
  {
    "regNumber": "U19CS1061",
    "fullName": "Ismail Abubakar",
    "faculty": "Science",
    "department": "Computer Science",
    "admissionYear": 2021,
    "expectedGraduationYear": 2025,
    "gender": "Not Specified",
    "phoneNumber": "",
    "email": "u19cs1061@university.edu.ng",
    "dateOfBirth": "2000-01-01",
    "stateOfOrigin": "Unknown",
    "address": "Campus Hostel",
    "nextOfKin": "Unknown",
    "nextOfKinGSM": "",
    "nextOfKinAddress": ""
  }
];
