GET http://localhost:3000/api/users/68b20e21390e9644dfd9a899/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIyMGUyMTM5MGU5NjQ0ZGZkOWE4OTkiLCJlbWFpbCI6IndhbHd5ZGVAZ21haWwuY29tIiwiaWF0IjoxNzU2NTYxNjg2LCJleHAiOjE3NTcxNjY0ODZ9.rkO16gW4yGdeWqZzJhcoZW7XiEaz5QoZ9zlPRiRRJhE